### ISSUE TITLE
Stopped working today after VSCode update

### ISSUE THREAD

**Issue by cinicola** [JosephAllen/apex-code-runner#48]
I'm pressing "Apex: Refresh Access Token", but the option "Execute Anonymous" doesn't appear after that. There is no error messages.

**Comment by JosephAllen** [comment]
Thanks for reporting this!

What version of the CLI are you running?

`SFDX --version`

Are you able to authorize an org from VS Code?

**Comment by JosephAllen** [comment]
@cinicola,

I think we are good to go. I needed to update the code for the latest version of the CLI.

Can you make sure you have v0.1.7 of the code runner extension installed?

**Comment by cinicola** [comment]
@JosephAllen Hello! It's working now! Thank you!
